### ISSUE TITLE
Replacement String - corresponding length

### ISSUE THREAD

**Issue by tebaly** [SpoonX/Censoring#10]
> Call me on 555-123456, or send an email to me[at]example(dot)com.

It would be nice to be able to transform

_Call me on *******, or send an email to *****************._

**Comment by RWOverdijk** [comment]
I guess this is an option that could be added. I don't see the use, but if you do, feel free! :)

**Comment by RWOverdijk** [comment]
I just added this, sort of. You can define your own replacement function. The example for this specifric use case is in the readme

```js
scan.setReplacementString((match) => '*'.repeat(match.length));
```
